### ISSUE TITLE
404 on redirect from Eclipse Jetty Documentation

### ISSUE THREAD

**Issue by janbartel** [jetty/jetty.website#50]
http://www.eclipse.org/jetty/documentation/ redirects to https://jetty.org/documentation/ and yields a 404 Not Found.

**Comment by jmcc0nn3ll** [comment]
I'll have to add another rule on the jetty.org virtual host, deep links should work but I guess this one didn't.

**Comment by jmcc0nn3ll** [comment]
Fixed!

**Comment by joakime** [comment]
Still broken.

If I follow an old URI, like https://eclipse.dev/jetty/documentation/jetty-9/index.html

**Comment by jmcc0nn3ll** [comment]
We have no jetty-9 documentation published

**Comment by joakime** [comment]
> We have no jetty-9 documentation published

Ones that do not exist should redirect to the documentation home page.
https://jetty.org/docs/index.html

**Comment by jmcc0nn3ll** [comment]
Fair enough I'll take care of it

**Comment by jmcc0nn3ll** [comment]
/documentation - check
/documentation/index.html - check
/documentation/jetty-9 - check
/documentation/jetty-9/goop.html - check
